### ISSUE TITLE
data race

### ISSUE THREAD

**Issue by Chr-ss** [sairutra/philosophers#5]
use -g3 -fsanitize=thread on CC for object files and the executable

veno@Veno:~/github/sebas_philo/philo$ ./build/bin/philo 2 310 100 100 5
1 1 has taken a fork
1 1 has taken a fork
1 1 is eating
==================
WARNING: ThreadSanitizer: data race (pid=6187)
  Read of size 8 at 0x7b1000000038 by main thread:
    #0 thread_monitor src/main.c:345 (philo+0x2b5e)
    #1 thread_init src/main.c:378 (philo+0x2dc3)
    #2 main src/main.c:416 (philo+0x3051)

  Previous write of size 8 at 0x7b1000000038 by thread T1 (mutexes: write M1, write M0, write M2):
    #0 routine_print src/main.c:192 (philo+0x1faa)
    #1 routine src/main.c:263 (philo+0x2513)

  As if synchronized via sleep:
    #0 usleep ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:359 (libtsan.so.0+0x66547)
    #1 thread_init src/main.c:375 (philo+0x2d97)
    #2 main src/main.c:416 (philo+0x3051)

  Location is heap block of size 64 at 0x7b1000000000 allocated by main thread:
    #0 malloc ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:655 (libtsan.so.0+0x31c57)
    #1 thread_init_philo src/main.c:282 (philo+0x2646)
    #2 thread_init src/main.c:373 (philo+0x2d82)
    #3 main src/main.c:416 (philo+0x3051)

  Mutex M1 (0x7b1400000028) created at:
    #0 pthread_mutex_init ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1227 (libtsan.so.0+0x4bee1)
    #1 mutex_init src/main.c:167 (philo+0x1db8)
    #2 main src/main.c:414 (philo+0x3022)

  Mutex M0 (0x7b1400000000) created at:
    #0 pthread_mutex_init ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1227 (libtsan.so.0+0x4bee1)
    #1 mutex_init src/main.c:167 (philo+0x1db8)
    #2 main src/main.c:414 (philo+0x3022)

  Mutex M2 (0x7ffc391ad320) created at:
    #0 pthread_mutex_init ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1227 (libtsan.so.0+0x4bee1)
    #1 mutex_init src/main.c:171 (philo+0x1e10)
    #2 main src/main.c:414 (philo+0x3022)

  Thread T1 (tid=6189, running) created by main thread at:
    #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:969 (libtsan.so.0+0x605b8)
    #1 thread_init_philo src/main.c:301 (philo+0x28dc)
    #2 thread_init src/main.c:373 (philo+0x2d82)
    #3 main src/main.c:416 (philo+0x3051)

SUMMARY: ThreadSanitizer: data race src/main.c:345 in thread_monitor
==================
==================
WARNING: ThreadSanitizer: data race (pid=6187)
  Read of size 4 at 0x7b1000000030 by main thread:
    #0 thread_monitor src/main.c:347 (philo+0x2c35)
    #1 thread_init src/main.c:378 (philo+0x2dc3)
    #2 main src/main.c:416 (philo+0x3051)

  Previous write of size 4 at 0x7b1000000030 by thread T1 (mutexes: write M1, write M0, write M2):
    #0 routine_print src/main.c:189 (philo+0x1f4f)
    #1 routine src/main.c:263 (philo+0x2513)

  As if synchronized via sleep:
    #0 usleep ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:359 (libtsan.so.0+0x66547)
    #1 thread_init src/main.c:375 (philo+0x2d97)
    #2 main src/main.c:416 (philo+0x3051)

  Location is heap block of size 64 at 0x7b1000000000 allocated by main thread:
    #0 malloc ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:655 (libtsan.so.0+0x31c57)
    #1 thread_init_philo src/main.c:282 (philo+0x2646)
    #2 thread_init src/main.c:373 (philo+0x2d82)
    #3 main src/main.c:416 (philo+0x3051)

  Mutex M1 (0x7b1400000028) created at:
    #0 pthread_mutex_init ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1227 (libtsan.so.0+0x4bee1)
    #1 mutex_init src/main.c:167 (philo+0x1db8)
    #2 main src/main.c:414 (philo+0x3022)

  Mutex M0 (0x7b1400000000) created at:
    #0 pthread_mutex_init ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1227 (libtsan.so.0+0x4bee1)
    #1 mutex_init src/main.c:167 (philo+0x1db8)
    #2 main src/main.c:414 (philo+0x3022)

  Mutex M2 (0x7ffc391ad320) created at:
    #0 pthread_mutex_init ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1227 (libtsan.so.0+0x4bee1)
    #1 mutex_init src/main.c:171 (philo+0x1e10)
    #2 main src/main.c:414 (philo+0x3022)

  Thread T1 (tid=6189, running) created by main thread at:
    #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:969 (libtsan.so.0+0x605b8)
    #1 thread_init_philo src/main.c:301 (philo+0x28dc)
    #2 thread_init src/main.c:373 (philo+0x2d82)
    #3 main src/main.c:416 (philo+0x3051)

SUMMARY: ThreadSanitizer: data race src/main.c:347 in thread_monitor
==================
==================
WARNING: ThreadSanitizer: data race (pid=6187)
  Read of size 8 at 0x7b1000000078 by main thread:
    #0 thread_monitor src/main.c:345 (philo+0x2b5e)
    #1 thread_init src/main.c:378 (philo+0x2dc3)
    #2 main src/main.c:416 (philo+0x3051)

  Previous write of size 8 at 0x7b1000000078 by thread T2:
    #0 routine src/main.c:256 (philo+0x24ba)

  As if synchronized via sleep:
    #0 usleep ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:359 (libtsan.so.0+0x66547)
    #1 thread_init src/main.c:375 (philo+0x2d97)
    #2 main src/main.c:416 (philo+0x3051)

  Location is heap block of size 64 at 0x7b1000000040 allocated by main thread:
    #0 malloc ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:655 (libtsan.so.0+0x31c57)
    #1 thread_init_philo src/main.c:282 (philo+0x2646)
    #2 thread_init src/main.c:373 (philo+0x2d82)
    #3 main src/main.c:416 (philo+0x3051)

  Thread T2 (tid=6190, running) created by main thread at:
    #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:969 (libtsan.so.0+0x605b8)
    #1 thread_init_philo src/main.c:301 (philo+0x28dc)
    #2 thread_init src/main.c:373 (philo+0x2d82)
    #3 main src/main.c:416 (philo+0x3051)

SUMMARY: ThreadSanitizer: data race src/main.c:345 in thread_monitor
==================
101 1 is sleeping
==================
WARNING: ThreadSanitizer: data race (pid=6187)
  Write of size 4 at 0x7b1000000070 by thread T2 (mutexes: write M0, write M2):
    #0 routine_print src/main.c:189 (philo+0x1f4f)
    #1 routine_lock src/main.c:224 (philo+0x237f)
    #2 routine src/main.c:261 (philo+0x24f4)

  Previous read of size 4 at 0x7b1000000070 by main thread:
    [failed to restore the stack]

  Location is heap block of size 64 at 0x7b1000000040 allocated by main thread:
    #0 malloc ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:655 (libtsan.so.0+0x31c57)
    #1 thread_init_philo src/main.c:282 (philo+0x2646)
    #2 thread_init src/main.c:373 (philo+0x2d82)
    #3 main src/main.c:416 (philo+0x3051)

  Mutex M0 (0x7b1400000000) created at:
    #0 pthread_mutex_init ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1227 (libtsan.so.0+0x4bee1)
    #1 mutex_init src/main.c:167 (philo+0x1db8)
    #2 main src/main.c:414 (philo+0x3022)

  Mutex M2 (0x7ffc391ad320) created at:
    #0 pthread_mutex_init ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1227 (libtsan.so.0+0x4bee1)
    #1 mutex_init src/main.c:171 (philo+0x1e10)
    #2 main src/main.c:414 (philo+0x3022)

  Thread T2 (tid=6190, running) created by main thread at:
    #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:969 (libtsan.so.0+0x605b8)
    #1 thread_init_philo src/main.c:301 (philo+0x28dc)
    #2 thread_init src/main.c:373 (philo+0x2d82)
    #3 main src/main.c:416 (philo+0x3051)

SUMMARY: ThreadSanitizer: data race src/main.c:189 in routine_print
==================
102 2 has taken a fork
==================
WARNING: ThreadSanitizer: lock-order-inversion (potential deadlock) (pid=6187)
  Cycle in lock order graph: M1 (0x7b1400000028) => M0 (0x7b1400000000) => M1

  Mutex M0 acquired here while holding mutex M1 in thread T1:
    #0 pthread_mutex_lock ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:4240 (libtsan.so.0+0x53908)
    #1 routine_lock src/main.c:225 (philo+0x239f)
    #2 routine src/main.c:261 (philo+0x24f4)

    Hint: use TSAN_OPTIONS=second_deadlock_stack=1 to get more informative warning message

  Mutex M1 acquired here while holding mutex M0 in thread T2:
    #0 pthread_mutex_lock ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:4240 (libtsan.so.0+0x53908)
    #1 routine_lock src/main.c:225 (philo+0x239f)
    #2 routine src/main.c:261 (philo+0x24f4)

  Thread T1 (tid=6189, running) created by main thread at:
    #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:969 (libtsan.so.0+0x605b8)
    #1 thread_init_philo src/main.c:301 (philo+0x28dc)
    #2 thread_init src/main.c:373 (philo+0x2d82)
    #3 main src/main.c:416 (philo+0x3051)

  Thread T2 (tid=6190, running) created by main thread at:
    #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:969 (libtsan.so.0+0x605b8)
    #1 thread_init_philo src/main.c:301 (philo+0x28dc)
    #2 thread_init src/main.c:373 (philo+0x2d82)
    #3 main src/main.c:416 (philo+0x3051)

SUMMARY: ThreadSanitizer: lock-order-inversion (potential deadlock) src/main.c:225 in routine_lock
==================
102 2 has taken a fork
102 2 is eating
201 1 is thinking
202 2 is sleeping
202 1 has taken a fork
202 1 has taken a fork
202 1 is eating
302 2 is thinking
302 1 is sleeping
302 2 has taken a fork
302 2 has taken a fork
302 2 is eating
402 1 is thinking
402 2 is sleeping
402 1 has taken a fork
402 1 has taken a fork
402 1 is eating
502 2 is thinking
502 1 is sleeping
502 2 has taken a fork
502 2 has taken a fork
502 2 is eating
602 1 is thinking
603 2 is sleeping
603 1 has taken a fork
603 1 has taken a fork
603 1 is eating
703 2 is thinking
703 1 is sleeping
703 2 has taken a fork
703 2 has taken a fork
703 2 is eating
803 1 is thinking
803 2 is sleeping
803 1 has taken a fork
803 1 has taken a fork
803 1 is eating
903 2 is thinking
903 2 has taken a fork
903 2 has taken a fork
903 2 is eating
ThreadSanitizer: reported 5 warnings

**Comment by Chr-ss** [comment]
#Link
$(TARGETDIR)/$(TARGET) : $(OBJECTS)
	$(CC) $(OBJECTS) -o  $(TARGETDIR)/$(TARGET) -g3 -fsanitize=thread

**Comment by sairutra** [comment]
fixed in 4127d9913acd93a78d3716a866d93ce8f0226918
